name: update-best-of-list

on:
  workflow_dispatch:
  schedule:
    - cron: '32 6 * * 6'  # At 06:32 every Saturday

permissions:
  contents: write
  pull-requests: write

jobs:
  update-best-of-list:
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v6
        with:
          branch: main
      - name: Install best-of-generator
        run: pip install git+https://github.com/ProperDocs/best-of-generator
      - name: Generate best-of list
        run: best-of generate projects.yaml --github-key=${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          add-paths: README.md
          commit-message: 'Update best-of list'
          title: 'Update best-of list'
          committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
          branch: update
